apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox # Penting: men-deploy ke namespace sandbox
spec:
  selector:
    app: techtrends # Service ini akan merutekan traffic ke Pod dengan label app: techtrends
  ports:
  - protocol: TCP
    port: 4111 # Port yang akan diekspos oleh Service
    targetPort: 3111 # Port di dalam container Pod yang akan dituju
  type: ClusterIP # Jenis Service: hanya dapat diakses dari dalam cluster